env:
  browser: true
  es2021: true
extends:
  - 'plugin:vue/vue3-recommended'
  - 'eslint:recommended'
  - '@vue/typescript/recommended'
parserOptions:
  ecmaVersion: 12
plugins:
  - vue
  - '@typescript-eslint'
rules: { 'vue/multi-word-component-names': 'off' }
# この記事を参考にeslintとPrettierを導入 https://zenn.dev/chida/articles/c0bd3ad56ed06b
